############################################
# build container
############################################
FROM maven:3-jdk-8-alpine as builder

COPY . /tmp

WORKDIR /tmp

RUN mvn clean package -DskipTests=true
############################################
# Runtime container
############################################
FROM openjdk:8-jre-alpine

EXPOSE 4567/tcp

COPY --from=builder /tmp/target/*.jar /app.jar

WORKDIR /

ENTRYPOINT ["/usr/bin/java","-jar", "/app.jar"]