version: '3'

services:
  traefik:
    image: traefik:1.7
    command: [
    "--web", 
    "--docker", 
    "--docker.domain=docker.localhost"
    ]
    depends_on:
    - "authentik"
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik-net:
      public-net:
    labels:
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:traefik.docker.localhost"
    - "traefik.frontend.auth.forward.address=http://authentik:4567/auth"
    - "traefik.frontend.auth.forward.trustForwardHeader=true"
    - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
    
  authentik:
    image: hermanosgecko/authentik:latest
    environment:
     - INSECURE_COOKIE=true  # Example assumes no https, do not use in production
     - COOKIE_DOMAIN=docker.localhost
     - AUTH_HOST=auth.docker.localhost 
     - SECRET=THIS_IS_A_SECRET 
    networks:
      traefik-net:
        aliases:
        - "authentik"
    volumes:
     - ${PWD}/htpasswd:/htpasswd:ro
    labels:
    - "traefik.port=4567"
    - "traefik.frontend.rule=Host:auth.docker.localhost"
#    - "traefik.frontend.auth.forward.address=http://authentik:4567/auth"
#    - "traefik.frontend.auth.forward.trustForwardHeader=true"
#    - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"

  whoami:
    image: stefanscherer/whoami:latest
    networks:
      traefik-net:
    labels:
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"
    - "traefik.frontend.auth.forward.address=http://authentik:4567/auth"
    - "traefik.frontend.auth.forward.trustForwardHeader=true"
    - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"


networks:
  traefik-net:
    internal: true
  public-net: